TEXTS = {
    "uz": {
        "subscribe_required": "📢 Ботдан фойдаланиш учун қуйидаги каналларга обуна бўлинг:",
        "subscribe_button": "✅ Обуна бўлдим",
        "not_subscribed": "❌ Сиз ҳали барча каналларга обуна бўлмагансиз!\n\nИлтимос, юқоридаги каналларга обуна бўлиб, сўнг «✅ Обуна бўлдим» тугмасини босинг.",

        "choose_lang": "🌐 Тилни танланг / Выберите язык:",
        "lang_uz": "🇺🇿 Ўзбек",
        "lang_ru": "🇷🇺 Русский",
        "lang_selected": "✅ Тил танланди: Ўзбек тили",

        "enter_name": "👤 Илтимос, исмингизни киритинг:",
        "enter_surname": "👤 Илтимос, фамилиянгизни киритинг:",
        "enter_phone": "📱 Илтимос, телефон рақамингизни юборинг:",
        "share_contact": "📲 Контактни улашиш",
        "registration_done": "✅ Рўйхатдан ўтиш муваффақиятли якунланди!\n\n👤 Исм: {name}\n👤 Фамилия: {surname}\n📱 Телефон: {phone}",

        "main_menu": "🏠 Асосий менью",
        "exchange": "💱 Валюта айирбошлаш",
        "rates": "📊 Курс",
        "partners": "👥 Ҳамёнлар",
        "referral": "👥 Реферал",
        "settings": "⚙️ Созламалар",
        "callback": "📞 Қайта алоқа",
        "transfers": "🔄 Алмашувлар",
        "guide": "📖 Қўлланма",

        "settings_menu": "⚙️ Созламалар",
        "change_lang": "🌐 Тилни ўзгартириш",
        "change_name": "✏️ Исмни ўзгартириш",
        "back": "🔙 Орқага",

        "exchange_menu": "💱 Валюта айирбошлаш бўлими",
        "rates_menu": "📊 Валюта курслари",
        "partners_menu": "👥 Ҳамёнлар бўлими",
        "referral_menu": "👥 Реферал тизими",
        "callback_menu": "📞 Қайта алоқа - тез орада жавоб берамиз",
        "transfers_menu": "🔄 Алмашувлар бўлими",
        "guide_menu": "📖 Қўлланма бўлими",

        "admin_panel": "👨‍💼 Админ панел",
        "add_channel": "➕ Канал қўшиш",
        "remove_channel": "➖ Канал ўчириш",
        "list_channels": "📋 Каналлар рўйхати",
        "users_count": "👥 Фойдаланувчилар сони",
        "send_all": "📨 Ҳаммага хабар юбориш",
        "no_channels": "📭 Ҳеч қандай канал қўшилмаган",
        "channel_added": "✅ Канал муваффақиятли қўшилди!",
        "channel_removed": "✅ Канал ўчирилди!",
        "channel_not_found": "❌ Канал топилмади",
        "enter_channel_id": "Канал рақамини киритинг (масалан: -1001234567890):",
        "enter_channel_link": "Канал ҳаволасини киритинг (масалан: https://t.me/kanalim):",
        "enter_channel_name": "Канал номини киритинг:",
        "enter_channel_id_remove": "Ўчирмоқчи бўлган канал рақамини киритинг:",
        "broadcast_message": "Барча фойдаланувчиларга юбориладиган хабарни киритинг:",
        "broadcast_done": "✅ Хабар {count} та фойдаланувчига юборилди!",
    },

    "ru": {
        "subscribe_required": "📢 Чтобы использовать бота, подпишитесь на следующие каналы:",
        "subscribe_button": "✅ Я подписался",
        "not_subscribed": "❌ Вы ещё не подписались на все каналы!\n\nПожалуйста, подпишитесь на каналы выше и нажмите «✅ Я подписался».",
        "choose_lang": "🌐 Тилни танланг / Выберите язык:",
        "lang_uz": "🇺🇿 Ўзбек",
        "lang_ru": "🇷🇺 Русский",
        "lang_selected": "✅ Язык выбран: Русский",
        "enter_name": "👤 Пожалуйста, введите ваше имя:",
        "enter_surname": "👤 Пожалуйста, введите вашу фамилию:",
        "enter_phone": "📱 Пожалуйста, отправьте ваш номер телефона:",
        "share_contact": "📲 Поделиться контактом",
        "registration_done": "✅ Регистрация успешно завершена!\n\n👤 Имя: {name}\n👤 Фамилия: {surname}\n📱 Телефон: {phone}",

        "main_menu": "🏠 Главное меню",
        "exchange": "💱 Обмен валют",
        "rates": "📊 Курс",
        "partners": "👥 Ҳамёнлар",
        "referral": "👥 Реферал",
        "settings": "⚙️ Настройки",
        "callback": "📞 Обратная связь",
        "transfers": "🔄 Переводы",
        "guide": "📖 Руководство",

        "settings_menu": "⚙️ Настройки",
        "change_lang": "🌐 Изменить язык",
        "change_name": "✏️ Изменить имя",
        "back": "🔙 Назад",

        "exchange_menu": "💱 Раздел обмена валют",
        "rates_menu": "📊 Курсы валют",
        "partners_menu": "👥 Ҳамёнлар бўлими",
        "referral_menu": "👥 Реферальная система",
        "callback_menu": "📞 Обратная связь - скоро ответим",
        "transfers_menu": "🔄 Раздел переводов",
        "guide_menu": "📖 Раздел руководства",

        "admin_panel": "👨‍💼 Панель администратора",
        "add_channel": "➕ Добавить канал",
        "remove_channel": "➖ Удалить канал",
        "list_channels": "📋 Список каналов",
        "users_count": "👥 Количество пользователей",
        "send_all": "📨 Отправить всем",
        "no_channels": "📭 Каналы не добавлены",
        "channel_added": "✅ Канал успешно добавлен!",
        "channel_removed": "✅ Канал удалён!",
        "channel_not_found": "❌ Канал не найден",
        "enter_channel_id": "Введите номер канала (например: -1001234567890):",
        "enter_channel_link": "Введите ссылку на канал (например: https://t.me/mycannel):",
        "enter_channel_name": "Введите название канала:",
        "enter_channel_id_remove": "Введите номер канала для удаления:",
        "broadcast_message": "Введите сообщение для отправки всем пользователям:",
        "broadcast_done": "✅ Сообщение отправлено {count} пользователям!",
    }
}

def t(lang: str, key: str, **kwargs) -> str:
    lang = lang if lang in TEXTS else "uz"
    text = TEXTS[lang].get(key, TEXTS["uz"].get(key, key))
    if kwargs:
        text = text.format(**kwargs)
    return text
